### PR TITLE
Fixes the body {} deprecation

### PR DESCRIPTION
**Pull request by burner**

### CODE REVIEW

**Review by PetarKirov — APPROVED** [review]

**Comment by burner** [comment]
I'm not sure why the CI fails but it looks like there is a problem fetching some libs on ubuntu

```
Failed to invoke the compiler /home/travis/dlang/ldc-1.27.0-beta1/bin/ldc2 to determine the build platform: /home/travis/dlang/ldc-1.27.0-beta1/bin/ldc2: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by /home/travis/dlang/ldc-1.27.0-beta1/bin/ldc2)
```

**Comment by qznc** [comment]
It is just the ldc-beta job which has an issue. It suggests to notify @wilzbach and @MartinNowak.

**Comment by wilzbach** [comment]
I don't think that the D setup for Travis is maintained anymore, so I would suggest to either switch CIs or disable the failing job

**Comment by qznc** [comment]
@burner could you just delete the "ldc-beta" line in .travis.yml? Then this should pass and we can merge it. I created #7 to resolve the CI aspect cleanly.

**Comment by burner** [comment]
@qznc sure

**Comment by burner** [comment]
done

**Comment by burner** [comment]
thank you

can I also get a new release?

**Comment by qznc** [comment]
Tagged it 3.0.2 now dub needs to recognize it.

**Comment by burner** [comment]
awesome thank you

**Pull request merged**
